import Link from "next/link";
import { ArtworkSlot } from "@/components/ArtworkSlot";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { ProjectRow } from "@/components/ProjectRow";
import { SectionLabel } from "@/components/SectionLabel";
import { processSteps, projects, services } from "@/data/projects";

export default function Home() {
  return <><Header /><main className="page-shell page-grid border-x border-[var(--line)]">
    <section className="home-hero product-hero grid gap-8 px-4 py-8 md:px-6 md:py-10 xl:grid-cols-[minmax(0,0.9fr)_minmax(420px,0.72fr)]">
      <div className="flex min-w-0 flex-col justify-between gap-12"><div><p className="mono mb-7 text-[var(--muted)]">01. Home / full-stack / responsive</p><h1 className="display hero-title home-title">MKZV<br />WEB</h1><p className="copy-lg mt-8 max-w-xl text-[var(--muted)]">Full-stack разработка для сайтов, сервисов и брендов. Собираю дизайн, интерфейс и логику в одну работающую систему.</p></div><div className="grid max-w-2xl gap-3 sm:grid-cols-2"><Link className="thin-button" href="/projects">Смотреть проекты <span aria-hidden="true">→</span></Link><Link className="thin-button" href="/contacts">Обсудить задачу <span aria-hidden="true">→</span></Link></div></div>
      <div className="hero-artwork self-stretch"><ArtworkSlot className="hero-sphere" wide /><p className="hero-artwork-note mono">Noise sphere / live loop<br />MKZV WEB / 2026</p></div>
    </section>
    <section className="section px-4 md:px-6"><SectionLabel index="02" title="Чем занимаюсь" /><div className="grid gap-3 lg:grid-cols-2">{services.map((service) => <article className="service-card panel min-w-0" data-index={service.meta} key={service.title}><p className="mono mb-10 text-[var(--muted)]">[{service.meta}]</p><h2 className="display service-title">{service.title}</h2><p className="copy mt-6 max-w-xl text-[var(--muted)]">{service.text}</p></article>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="03" title="Избранные проекты" /><div className="grid gap-3">{projects.map((project) => <ProjectRow key={project.id} project={project} />)}</div><Link className="thin-button mt-4 w-full" href="/projects">Показать все проекты <span aria-hidden="true">→</span></Link></section>
    <section className="section px-4 md:px-6"><SectionLabel index="04" title="Процесс" /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{processSteps.map((step, index) => <div className="process-card panel p-5" data-index={`0${index + 1}`} key={step}><p className="mono text-[var(--muted)]">0{index + 1}</p><p className="display mt-14 text-[clamp(1.55rem,2.2vw,2.65rem)]">{step}</p></div>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="04.1" title="Формат работы" /><div className="grid gap-3 lg:grid-cols-3"><article className="panel min-w-0 p-5"><p className="mono text-[var(--muted)]">01 / Старт</p><h2 className="display mt-8 text-[clamp(1.7rem,2.5vw,2.8rem)]">Сначала<br />разбираюсь</h2><p className="copy mt-6 text-[var(--muted)]">Фиксируем задачу, аудиторию, ограничения и действие, которое человек должен совершить на сайте.</p></article><article className="panel min-w-0 p-5"><p className="mono text-[var(--muted)]">02 / Сборка</p><h2 className="display mt-8 text-[clamp(1.7rem,2.5vw,2.8rem)]">Делаю<br />системно</h2><p className="copy mt-6 text-[var(--muted)]">Структура, дизайн, frontend, интеграции и адаптив собираются в единую рабочую среду.</p></article><article className="panel min-w-0 p-5"><p className="mono text-[var(--muted)]">03 / После</p><h2 className="display mt-8 text-[clamp(1.7rem,2.5vw,2.8rem)]">Не бросаю<br />после запуска</h2><p className="copy mt-6 text-[var(--muted)]">Оставляю понятную основу для развития: чистый код, документацию и место для новых страниц.</p></article></div></section>
    <section className="signal-teaser section relative overflow-hidden px-4 md:px-6"><ArtworkSlot className="teaser-sphere" /><div className="relative z-10 grid gap-8 xl:grid-cols-[minmax(0,0.72fr)_minmax(320px,0.44fr)]"><div><p className="mono mb-5 text-[var(--muted)]">05. Signal / side project</p><h2 className="display signal-title">Noise in<br />the system</h2></div><div className="self-end"><p className="copy-lg text-[var(--muted)]">Музыка, биты и шум — отдельный слой MKZV. Он не спорит с портфолио, а добавляет ему характер.</p><Link className="thin-button mt-7" href="/signal">Открыть Signal <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="home-cta grid gap-7 px-4 py-10 md:grid-cols-[minmax(0,1fr)_auto] md:px-6"><p className="display case-card-title">Есть проект?<br />Давай соберём.</p><Link className="thin-button self-end" href="/contacts">Перейти к форме <span aria-hidden="true">→</span></Link></section>
  </main><Footer /></>;
}
