import Link from "next/link";
import { ArtworkSlot } from "@/components/ArtworkSlot";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { PingPongVideo } from "@/components/PingPongVideo";
import { ProjectRow } from "@/components/ProjectRow";
import { SectionLabel } from "@/components/SectionLabel";
import { VisualPlaceholder } from "@/components/VisualPlaceholder";
import {
  audiences,
  clientSignals,
  deliverables,
  faqItems,
  launchChecklist,
  marketEdges,
  offerPoints,
  packages,
  pageRoute,
  processSteps,
  projects,
  services,
  siteNotes,
  tgptPreview,
  trustItems,
} from "@/data/projects";

export default function Home() {
  return <><Header /><main className="page-shell page-grid border-x border-[var(--line)]">
    <section className="home-hero product-hero grid gap-8 px-4 py-8 md:px-6 md:py-10 xl:grid-cols-[minmax(0,0.9fr)_minmax(420px,0.72fr)]">
      <div className="flex min-w-0 flex-col justify-between gap-12"><div><p className="mono mb-7 text-[var(--muted)]">01. Home / sites that sell / full-stack</p><h1 className="display hero-title home-title">MKZV<br />WEB</h1><p className="copy-lg mt-8 max-w-2xl text-[var(--muted)]">Собираю сайты, которые выглядят дорого, быстро объясняют услугу и ведут человека к заявке. Дизайн, код и запуск — в одной связке.</p><div className="hero-proof mt-8 grid gap-3 sm:grid-cols-3"><p className="mono">Сайт под ключ</p><p className="mono">Mobile first</p><p className="mono">Форма / TGPT позже</p></div></div><div className="grid max-w-2xl gap-3 sm:grid-cols-2"><Link className="thin-button" href="/contacts">Обсудить сайт <span aria-hidden="true">→</span></Link><Link className="thin-button" href="/projects">Смотреть подход <span aria-hidden="true">→</span></Link></div></div>
      <div className="hero-artwork hero-artwork-test self-stretch">
        <PingPongVideo className="hero-video-sphere" src="/media/particle-sphere-header-test.mp4" />
        <p className="hero-artwork-note mono">Header sphere / ping-pong test<br />MKZV WEB / 2026</p>
      </div>
    </section>
    <section className="section px-4 md:px-6"><SectionLabel index="02" title="Быстрые сигналы" /><div className="signal-metrics grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{clientSignals.map((item) => <article className="metric-tile panel min-w-0" key={item.value}><p className="display metric-value">{item.value}</p><p className="mono metric-label">{item.label}</p></article>)}</div><div className="visual-break mt-3 grid gap-3 lg:grid-cols-[minmax(0,0.68fr)_minmax(0,0.32fr)]"><VisualPlaceholder label="first screen / ux" title="Оффер без шума" variant="screen" /><VisualPlaceholder label="mobile first" title="Заявка на телефоне" variant="mobile" /></div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="03" title="Что покупают" /><div className="grid gap-3 lg:grid-cols-2">{services.map((service) => <article className="service-card panel min-w-0" data-index={service.meta} key={service.title}><p className="mono mb-10 text-[var(--muted)]">[{service.meta}]</p><h2 className="display service-title">{service.title}</h2><p className="copy mt-6 max-w-xl text-[var(--muted)]">{service.text}</p></article>)}</div><div className="visual-break mt-3 grid gap-3 lg:grid-cols-[minmax(0,0.55fr)_minmax(0,0.45fr)]"><VisualPlaceholder label="site preview / placeholder" title="Экран услуги" variant="screen" /><VisualPlaceholder label="system map / placeholder" title="UI + код + форма" variant="system" /></div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="04" title="Маршрут страницы" /><div className="route-showcase grid gap-3 xl:grid-cols-[minmax(280px,0.42fr)_minmax(0,1fr)]"><VisualPlaceholder label="route map / lead path" title="Путь до заявки" variant="route" /><div className="route-line grid gap-3 lg:grid-cols-4">{pageRoute.map((item, index) => <article className="route-card panel min-w-0 p-5" key={item.title}><p className="mono flex items-center justify-between text-[var(--muted)]"><span>0{index + 1}</span><span>{item.tag}</span></p><h2 className="display mt-10 text-[clamp(1.35rem,2vw,2.35rem)]">{item.title}</h2><p className="copy mt-5 text-[var(--muted)]">{item.text}</p></article>)}</div></div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="05" title="Кому подойдёт" /><div className="audience-grid grid gap-3 md:grid-cols-2 xl:grid-cols-4">{audiences.map((item, index) => <article className="audience-card panel min-w-0 p-5" key={item.title}><p className="mono text-[var(--muted)]">0{index + 1} / клиент</p><h2 className="display mt-9 text-[clamp(1.55rem,2.2vw,2.75rem)]">{item.title}</h2><p className="copy mt-5 text-[var(--muted)]">{item.text}</p></article>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="06" title="Почему это работает" /><div className="grid gap-3 lg:grid-cols-3">{offerPoints.map((point, index) => <article className="sell-card panel min-w-0 p-5" key={point.title}><p className="mono text-[var(--muted)]">0{index + 1} / отличие</p><h2 className="display mt-8 text-[clamp(1.45rem,2vw,2.35rem)]">{point.title}</h2><p className="copy mt-5 text-[var(--muted)]">{point.text}</p></article>)}</div><div className="trust-strip mt-3 grid gap-3 lg:grid-cols-4">{trustItems.map((item) => <p className="mono panel min-w-0 p-4 leading-5 text-[var(--paper)]" key={item}>{item}</p>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="07" title="Не как у всех" /><div className="market-grid grid gap-3 lg:grid-cols-3">{marketEdges.map((edge) => <article className="market-card panel min-w-0 p-5" key={edge.label}><p className="mono text-[var(--paper)]">{edge.label}</p><div className="mt-8 grid gap-5"><p className="copy text-[var(--muted)]"><span className="mono block text-[var(--muted-2)]">Обычно</span>{edge.pain}</p><p className="copy text-[var(--paper)]"><span className="mono block text-[var(--muted-2)]">MKZV WEB</span>{edge.mkzv}</p></div></article>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="08" title="Избранные проекты" /><div className="visual-break mb-3 grid gap-3 lg:grid-cols-[minmax(0,0.62fr)_minmax(0,0.38fr)]"><VisualPlaceholder label="case poster / placeholder" title="Здесь будут реальные кейсы" variant="poster" /><VisualPlaceholder label="result signal / placeholder" title="Рост доверия" variant="wave" /></div><div className="grid gap-3">{projects.map((project) => <ProjectRow key={project.id} project={project} />)}</div><Link className="thin-button mt-4 w-full" href="/projects">Показать все проекты <span aria-hidden="true">→</span></Link></section>
    <section className="section px-4 md:px-6"><SectionLabel index="09" title="Что входит" /><div className="grid gap-3 lg:grid-cols-4">{deliverables.map((item, index) => <article className="deliverable-card panel min-w-0 p-5" key={item.title}><p className="mono text-[var(--muted)]">0{index + 1}</p><h2 className="display mt-10 text-[clamp(1.45rem,2vw,2.3rem)]">{item.title}</h2><p className="copy mt-5 text-[var(--muted)]">{item.text}</p></article>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="10" title="Форматы" /><div className="grid gap-3 lg:grid-cols-3">{packages.map((item, index) => <article className="package-card panel min-w-0 p-5" key={item.title}><p className="mono text-[var(--muted)]">0{index + 1} / формат</p><h2 className="display mt-8 text-[clamp(1.7rem,2.45vw,3rem)]">{item.title}</h2><p className="copy mt-4 text-[var(--muted)]">{item.subtitle}</p><ul className="mt-8 grid gap-3">{item.items.map((point) => <li className="mono package-point" key={point}>{point}</li>)}</ul></article>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="11" title="Процесс" /><div className="process-strip grid gap-3">{processSteps.map((step, index) => <div className="process-card panel p-5" data-index={`0${index + 1}`} key={step}><p className="mono text-[var(--muted)]">0{index + 1}</p><p className="display process-step-title mt-14">{step}</p></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{launchChecklist.map((item) => <p className="check-chip mono panel p-4 text-[var(--paper)]" key={item}>{item}</p>)}</div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="12" title="Как стартуем" /><div className="start-showcase grid gap-3 xl:grid-cols-[minmax(0,1fr)_minmax(320px,0.42fr)]"><div className="grid gap-3 lg:grid-cols-3">{siteNotes.map((item, index) => <article className="panel min-w-0 p-5" key={item.title}><p className="mono text-[var(--muted)]">0{index + 1} / точка</p><h2 className="display mt-8 text-[clamp(1.45rem,2.1vw,2.45rem)]">{item.title}</h2><p className="copy mt-6 text-[var(--muted)]">{item.text}</p></article>)}</div><VisualPlaceholder label="workflow / placeholder" title="Бриф → макет → запуск" variant="route" /></div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="13" title="TGPT позже" /><div className="tgpt-panel panel grid gap-7 p-5 lg:grid-cols-[minmax(0,0.72fr)_minmax(280px,0.48fr)]"><div><p className="mono text-[var(--muted)]">Next step / заявки</p><h2 className="display mt-8 text-[clamp(2rem,4vw,5rem)]">Форма станет<br />локальным TGPT</h2></div><div className="self-end"><p className="copy text-[var(--muted)]">Сейчас форма визуальная. Следующий этап — локальный приёмщик заявок: сайт собрал данные, Telegram получил сообщение, ты быстро ответил клиенту.</p><div className="mt-7 grid gap-2">{tgptPreview.map((item, index) => <p className="mono package-point" key={item}>0{index + 1} / {item}</p>)}</div></div></div></section>
    <section className="section px-4 md:px-6"><SectionLabel index="14" title="Вопросы" /><div className="grid gap-3 lg:grid-cols-3">{faqItems.map((item, index) => <article className="faq-card panel min-w-0 p-5" key={item.question}><p className="mono text-[var(--muted)]">0{index + 1} / вопрос</p><h2 className="display mt-8 text-[clamp(1.25rem,1.75vw,2.1rem)]">{item.question}</h2><p className="copy mt-5 text-[var(--muted)]">{item.answer}</p></article>)}</div></section>
    <section className="signal-teaser section relative overflow-hidden px-4 md:px-6"><ArtworkSlot className="teaser-sphere" /><div className="relative z-10 grid gap-8 xl:grid-cols-[minmax(0,0.72fr)_minmax(320px,0.44fr)]"><div><p className="mono mb-5 text-[var(--muted)]">15. Signal / side project</p><h2 className="display signal-title">Noise in<br />the system</h2></div><div className="self-end"><p className="copy-lg text-[var(--muted)]">Музыка и шум добавляют сайту личный слой. Не шаблон. Не стерильная студия. MKZV.</p><Link className="thin-button mt-7" href="/signal">Открыть Signal <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="home-cta grid gap-7 px-4 py-10 md:grid-cols-[minmax(0,1fr)_auto] md:px-6"><p className="display case-card-title">Нужен сайт,<br />который продаёт?</p><Link className="thin-button self-end" href="/contacts">Написать о проекте <span aria-hidden="true">→</span></Link></section>
  </main><Footer /></>;
}
